### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by Mike-Torres**

### CODE REVIEW

**Comment by BryanSmith33** [comment]
Hello Michael,

It looks like you didn't fork the assessment and are trying to push the the DevMountain version. Please meet with your Basecamp mentor to review your answers and in the future be sure to fork a copy onto your github user

**Comment by Mike-Torres** [comment]
Good Afternoon, 
That was the first time ever using GitHub. Also, I have not been assigned a mentor yet.  If you could please provide me with my mentor name or email that would be great. I would like to know GitHub very well before I get up there. Thanks

Best,
Mike Torres     On Monday, November 5, 2018, 10:12:47 AM EST, Bryan Smith <notifications@github.com> wrote:  
 
 
Hello Michael,

It looks like you didn't fork the assessment and are trying to push the the DevMountain version. Please meet with your Basecamp mentor to review your answers and in the future be sure to fork a copy onto your github user

**Comment by BryanSmith33** [comment]
You will be assigned a mentor 6 weeks from your start date. In the future, remember to create a fork when necessary.

**Comment by Mike-Torres** [comment]
Bryan, 
Is there a time I can connect with you? As a first time learner of git, the terminology is something that I'm not too sure of.  The code is good, I checked it with my mentor in the industry for 20 years.  I went through the video, actually changed from sublime text to atom because of the git features, which I like.  I was hoping to be able to work with someone eventually to understand Git and Bash.  I have a few companies interested in me after graduating already in FL that told me that I need to have a full understanding of Git and Bash before they'd hire me. 
I've connected with you via LinkedIn as well.  Good to work with you and thank you for the feedback. 
Best, 
Mike 
    On Monday, November 5, 2018, 6:39:28 PM EST, Bryan Smith <notifications@github.com> wrote:  
 
 
You will be assigned a mentor 6 weeks from your start date. In the future, remember to create a fork when necessary.

**Pull request closed without merging**
